version: "3.8"
services:
  aet-rpa:
    image: aet-rpa:latest
    networks:
      - minha_rede
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_AUTH_EMAIL=${SUPABASE_AUTH_EMAIL}
      - SUPABASE_AUTH_PASSWORD=${SUPABASE_AUTH_PASSWORD}
      - SIAET_CODIGO_ACESSO=${SIAET_CODIGO_ACESSO}
      - SIAET_SENHA=${SIAET_SENHA}
      - AET_RPA_API_TOKEN=${AET_RPA_API_TOKEN}
    volumes:
      - aet-rpa-pdfs:/app/pdfs
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=minha_rede"
        - "traefik.http.routers.aet-rpa.rule=Host(`aet-rpa.pulse4mind.com`)"
        - "traefik.http.routers.aet-rpa.entrypoints=websecure"
        - "traefik.http.routers.aet-rpa.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.aet-rpa.loadbalancer.server.port=3000"
      replicas: 1
      resources:
        limits:
          memory: 2G
networks:
  minha_rede:
    external: true
volumes:
  aet-rpa-pdfs: